development:
  adapter: postgresql
  database: munchnow_development
  pool: 5
  timeout: 5000
  username: Christopher

test:
  adapter: postgresql
  database: munchnow_test
  pool: 5
  timeout: 5000
  username: Christopher

production:
  adapter: postgresql
  database: munchnow_production
  pool: 5
  timeout: 5000


